### ISSUE TITLE
Examples are broken?

### ISSUE THREAD

**Issue by TheBB** [evalf/nutils#453]
```
-> % python examples/cylinderflow.py
nutils v5.0 "farfalle" (git:3c7b0f5)
start Fri Aug 23 16:27:52 2019
Traceback (most recent call last):
  File "/home/eivind/repos/nutils/nutils/cli.py", line 176, in call
    func(**kwargs)
  File "examples/cylinderflow.py", line 29, in main
    nutils.log.info('creating {}x{} mesh, outer radius {:.2f}'.format(melems, nelems, .5*numpy.exp(elemangle*melems)))
AttributeError: module 'nutils.log' has no attribute 'info'
```

**Comment by joostvanzwieten** [comment]
Yes, that's caused by an updated version of module treelog. To fix you can use Nutils branch v5.x. We will release v5.1 very soon.

**Comment by joostvanzwieten** [comment]
v5.1 has been released. If the problem persists, please reopen this issue.
